### ISSUE TITLE
no attribute SafeConfigParser

### ISSUE THREAD

**Issue by OboTheHobo** [TheDrHax/ds4drv-cemuhook#20]
Possible issue with deprecation? Not entirely sure.

```Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/owen/.local/lib/python3.12/site-packages/ds4drv/__main__.py", line 6, in <module>
    from .actions import ActionRegistry
  File "/home/owen/.local/lib/python3.12/site-packages/ds4drv/actions/__init__.py", line 1, in <module>
    from ..action import ActionRegistry
  File "/home/owen/.local/lib/python3.12/site-packages/ds4drv/action.py", line 1, in <module>
    from .config import add_controller_option
  File "/home/owen/.local/lib/python3.12/site-packages/ds4drv/config.py", line 84, in <module>
    class Config(configparser.SafeConfigParser):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
````

Worked fine a month or two ago, now I get this when I try and run the program.

**Comment by OboTheHobo** [comment]
Replacing SafeConfigParser with ConfigParser fixes the issue. Opened a pull request for the change.

Worth noting that I think that change makes it incompatible with Python 2.X.
